### ISSUE TITLE
Exposes filesystem of the developer

### ISSUE THREAD

**Issue by formula1** [cheton/browserify-css#17]
https://github.com/cheton/browserify-css/blob/master/index.js#L67

It seems this has been done this way for the examples to work properly. However, by exposing the direct filepath you are also exposing the Developers filesystem. This may be simply an annoyance at times but could result in something far worse depending on how /super/secret/the/file/system/is.

Whats worse is that anyone using this module may have no idea they are exposing themselves like this. You may keep this if you don't want to rewrite the examples, however please notify people the path to the browserify-css module will be fully exposed.

Something like changing it to just `require("browserify-css")` will also reduce unnecessary diffs since I generally don't consider a browserified distro dirty just because the namespaces are different for requires that end up being numbers anyway.

**Comment by cheton** [comment]
Thanks for reminding me. I saw your PR yesterday. but it cannot pass the local build.
Could you try again using the following code example?

```javascript
cssTransform(options, filename, function(data) {
    var requirePath = path.relative(path.dirname(filename), __dirname);
    // leave out
    if (options.autoInjectOptions['verbose']) {
        moduleBody = 'var css = ' + JSON.stringify(data) + '; (require(' + JSON.stringify('./' + requirePath) + ').createStyle(css, { "href": ' + JSON.stringify(href) + '})); module.exports = css;';
    } else {
        moduleBody = 'var css = ' + JSON.stringify(data) + '; (require(' + JSON.stringify('./' + requirePath) + ').createStyle(css)); module.exports = css;';
    }
    // leave out
}
```

**Comment by formula1** [comment]
`./../../../node_modules/browserify-css"` Better, not pretty though :P 

Are there tests running on travis that aren't available for me to test? More likely than not I would assume the person has browserify-css installed in a requireable place. I was also considering something like [this](https://github.com/cheton/browserify-css/blob/master/test/main.js#L13) but seems you already beat me to it. `"browserify-css"` works fine for me locally and all the tests pass too which I'm confused about.

```
//Stuff before #61
                    if (options.autoInjectOptions['verbose']) {
                        moduleBody = 'var css = ' + JSON.stringify(data) + '; (require("browserify-css").createStyle(css, { "href": ' + JSON.stringify(href) + '})); module.exports = css;';
                    } else {
                        moduleBody = 'var css = ' + JSON.stringify(data) + '; (require("browserify-css").createStyle(css)); module.exports = css;';
                    }
//End Stuff

```

**Comment by cheton** [comment]
I found a way to fix the build error for my gulp task:
```diff
diff --git a/gulp/tasks/bundles.js b/gulp/tasks/bundles.js
index 7867a27..a65a569 100644
--- a/gulp/tasks/bundles.js
+++ b/gulp/tasks/bundles.js
@@ -19,6 +19,7 @@ module.exports = function(options) {
             return browserify(bundleConfig.options)
                 .add(bundleConfig.src)
                 .transform(require('../../index'), bundleTransform['browserify-css'])
+                .require('./browser', {expose: 'browserify-css'})
                 .bundle()
                 .pipe(exorcist(bundleMapFile))
                 .pipe(sourceStream(bundleFile))
```

Now we can simply use `require("browserify-css")` in `index.js` to avoid a lot of annonying relative paths in the require call like: `require('./../../../node_modules/browserify-css')`

I will make the new change in v0.6.0.

**Comment by cheton** [comment]
v0.6.x was published to npm: https://www.npmjs.com/package/browserify-css

**Comment by formula1** [comment]
Ah! The gulp file! of course T__T Thank you for being diligent, this saved me from using brfs + clean-css + a custom script I wrote to append it. Would much rather support something like this especially since it works with [disc](https://github.com/hughsk/disc).
