### ISSUE TITLE
emit 'file' event for import dependencies

### ISSUE THREAD

**Issue by mattdesl** [cheton/browserify-css#20]
Using `watchify`, you will not get a re-bundle if you make a change in a CSS dependency - i.e. a style sheet that was brought in with an `import()` statement. 

The solution for this tool is to emit a `file` event when a new dependency is discovered. See [here](https://github.com/substack/brfs/blob/master/index.js#L67) and [here](https://github.com/vuejs/vueify/pull/10/files).

Related:
https://github.com/mattdesl/budo/issues/57

**Comment by cheton** [comment]
Hi mattdesl,
Thanks for your reminding. I will check it out!

**Comment by cheton** [comment]
It's included in v0.7.1
https://github.com/cheton/browserify-css/releases/tag/v0.7.1
