### ISSUE TITLE
require(...).createStyle is not a function

### ISSUE THREAD

**Issue by codeskyblue** [cheton/browserify-css#23]
I use browserify-css in electron development. Got this error.

```
Uncaught TypeError: require(...).createStyle is not a function
```

Actually, I really not found createStyle definition. I don't know what wrong.

BTW: when I change the setting of browserify 
```
bundleExternal: false
```
The error happens

When I change to 

```
bundleExternal: true
```

The error dispears.

**Comment by cheton** [comment]
You can take a look at the following code:
https://github.com/cheton/browserify-css/blob/master/index.js#L66
```js
var css = '...'; // your css content
var href = '...';
require('browserify-css').createStyle(css, { "href": JSON.stringify(href)});
module.exports = css;
```

The browserify-css module transforms your `require('./xxx.css')` call to above one, and it requires  `browserify-css` module from the bundle.

So if you manually set the `bundleExternal` boolean option (which defaults to true) to false, the `browserify-css` module will not be bundled in the JS output file.

**Comment by cheton** [comment]
https://github.com/substack/node-browserify#browserifyfiles--opts
## browserify([files] [, opts])
`opts.bundleExternal` boolean option to set if external modules should be bundled. Defaults to true.

**Comment by codeskyblue** [comment]
@cheton I known the options. but my project not allow me to do that. I just want to known, how to solve the error, when I set bundleExternal to false.

**Comment by codeskyblue** [comment]
Just don't understand where is the createStyle function definition.

**Comment by cheton** [comment]
Browserify looks for a special “browser” field in the package.json. For example:
```json
{
  "browser": "./browser.js",
}
```

Calling `require('browserify-css')` will return the exports object defined by the browser field. You can find the exported `createStyle` function in above [browser.js](https://github.com/cheton/browserify-css/blob/master/browser.js).

**Comment by cheton** [comment]
https://github.com/cheton/browserify-css/blob/master/index.js#L62
A workaround way is to set the `autoInject` option to false, but your need to insert style tags by your own.
For example:
```js
[
    require('./styles/common.css'),
        :   :   :
    require('./index.css'),
].forEach(function(cssText){
    createStyles(cssText); // refer to the createStyle function defined in browser.js
});
```

**Comment by cheton** [comment]
```js
// Create a <style> tag with optional data attributes
var createStyle = function(cssText, attributes) {
    var head = document.head || document.getElementsByTagName('head')[0],
        style = document.createElement('style');

    style.type = 'text/css';
    for (var key in attributes) {
        if ( ! attributes.hasOwnProperty(key)) {
            continue;
        }
        var value = attributes[key];
        style.setAttribute('data-' + key, value);
    }
        
    if (style.sheet) { // for jsdom and IE9+
        style.innerHTML = cssText;
        style.sheet.cssText = cssText;
        head.appendChild(style);
    } else if (style.styleSheet) { // for IE8 and below
        head.appendChild(style);
        style.styleSheet.cssText = cssText;
    } else { // for Chrome, Firefox, and Safari
        style.appendChild(document.createTextNode(cssText));
        head.appendChild(style);
    }
};
```

**Comment by codeskyblue** [comment]
Thanks very much for your very quickly detailed response. thanks again.
