### ISSUE TITLE
Requiring CSS files from node_modules fails with SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Prinzhorn** [cheton/browserify-css#26]
Steps to reproduce in an empty folder

```
npm install browserify-css
npm install leaflet
echo 'require("leaflet/dist/leaflet.css")' > index.js
browserify index.js -t browserify-css -o bundle.js
```

> /tmp/leaflet-css/node_modules/leaflet/dist/leaflet.css:3
> .leaflet-map-pane,
> ^
> ParseError: Unexpected token

Copying the CSS file to the root works

```
cp node_modules/leaflet/dist/leaflet.css leaflet.css
echo 'require("./leaflet.css")' > index.js
browserify index.js -t browserify-css -o bundle.js
```

Is there anything we can do about it? Or does browserify treat these files differently and they don't even reach the transform?

**Comment by cheton** [comment]
You can try the following instead of directly requiring it from `node_modules`:
```bash
echo '@import url("node_modules/leaflet/dist/leaflet.css");' > index.css
echo "require('./index.css');" > index.js
browserify index.js -t browserify-css -o bundle.js
```

**Comment by cheton** [comment]
Note that the `-t` option will only transform module on top-level files.

In your case, you can use `browserify index.js -g browserify-css -o bundle.js` to transform module in the `node_modules` directory.

**Comment by Prinzhorn** [comment]
Thanks, with the `-g` option its working.

My actual setup uses package.json for defining tranforms like

```json
"browserify": {
    "transform": [
      "browserify-css"
    ]
},
```

as far as I can tell there is not way to define global transforms or set global to true using the package.json, right?

**Comment by cheton** [comment]
You can check out FAQ first at https://github.com/cheton/browserify-css#1-how-do-i-include-css-files-located-inside-the-node_modules-folder

Let's say if you want to require bootstrap.css within your project, you can use CSS @import rule as below:

**vendor.css:**

```css
/* Load CSS files from your node_modules folder */
@import "node_modules/bootstrap/dist/bootstrap.css";
```

**app.js:**
```js
require('./vendor.css');
```

However, in your case, you include an external module "angular-dialog-service" which requires css files in its index.js, unless you can manually add the following entry to its package.json file with a custom Gulp task:
```json
{
  "browserify": {
    "transform": ["browserify-css"]
  }
}
```

or `{ global: true }` is the only solution to transform CSS files within external modules.

**Comment by jlaustill** [comment]
I second that this should be front page and BOLD,  I just wasted a day until I found this issue.  This isn't obvious AT ALL...

**Comment by cheton** [comment]
Could someone help submit a PR to update README.md with respect to this issue? I would really appreciate it. Thanks.

**Comment by jlaustill** [comment]
I also figured out that you can use it with gulp, the api isn't documented well either

```javascript
.transform({global: true}, require("browserify-css"))
```

**Comment by lorenzfischer** [comment]
To add to the comment of @cheton, here's what I had to put to my browserify/babelify call to get this to work:

```
node_modules/.bin/browserify -g browserify-css \
-t [ babelify \
 --presets [ stage-0 es2015 react ] \
 --plugins [ transform-react-jsx transform-es2015-modules-umd ] ] \
path/to/my/app.jsx -o path/to/my/app.js
```
