### ISSUE TITLE
Difference between this and `cssify`?

### ISSUE THREAD

**Issue by jonscottclark** [cheton/browserify-css#34]
Hey @cheton,

Can you explain any differences/benefits between your package and https://github.com/davidguttman/cssify ? Just curious, thanks!

(Firstly, it seems like cssify doesn't include the clean-css transforms. Anything else?)

**Comment by cheton** [comment]
In addition to using `clean-css` for minifying CSS files, it can concatenate, inline, and rebase urls in CSS files using @import statements. For example:

index.css
```css
@import url("node_modules/bootstrap/dist/bootstrap.css");
@import url("components/foo/index.css");
body {
    background-color: #fff;
}
```
index.js
```js
require('./index.css');
```
The above code will produce only one &lt;style /&gt; tag within HTML.

The `browserify-css` transform also provides the [processRelativeUrl](https://github.com/cheton/browserify-css#processrelativeurl) option that allows you to copy font and image files within node_modules. Here is the Bootstrap example:
```
node_modules/
    bootstrap/
        dist/
            css/
                bootstrap.css
            fonts/
                glyphicons-halflings-regular.eot
                glyphicons-halflings-regular.svg
                glyphicons-halflings-regular.ttf
                glyphicons-halflings-regular.woff
                glyphicons-halflings-regular.woff2
```

You cam check out my sample code [here](https://github.com/cheton/browserify-css#2-how-do-i-load-font-and-image-files-from-node_modules).
