### ISSUE TITLE
Work on template literals, not just files

### ISSUE THREAD

**Issue by drschwabe** [cheton/browserify-css#39]
Would be handy if we could do: 

```require(`p { color:green }`)``` and have browserify-css do it's thing just like it would do if this was a separate CSS file.

**Comment by cheton** [comment]
Ｈi @drschwabe,

You can do this in your code:
```js
var styleText = `p { color: green }`;
require('browserify-css').createStyle(styleText);
```

browser.js:
https://github.com/cheton/browserify-css/blob/master/browser.js#L24

package.json:
https://github.com/cheton/browserify-css/blob/master/package.json#L6

**Comment by drschwabe** [comment]
Perfect!
