### ISSUE TITLE
--autoInject=false dont work in command line

### ISSUE THREAD

**Issue by liorwohl** [cheton/browserify-css#51]
its still injecting the css to the head of document

**Comment by cheton** [comment]
The value of the autoInject option is a string 'false' when passing from command line. It's necessary to convert a string to boolean for comparison. I will fix it soon.

**Comment by cheton** [comment]
You can use `--autoInject=0` as a workaround.

**Comment by cheton** [comment]
Fixed in v0.10.1

**Comment by liorwohl** [comment]
thanks :)
