### ISSUE TITLE
What is the benefit of autoInject=false

### ISSUE THREAD

**Issue by peterbarraud** [cheton/browserify-css#58]
I want to output the css to a separate file but not using `onFlush` option. Meaning I want to do this using the command line something like:
```
[ browserify-css --autoInject=false -o bundle.css ]
```
Is this possible?

**Comment by cheton** [comment]
Added in v0.13.0
https://github.com/cheton/browserify-css/releases/tag/v0.13.0

```js
browserify -t [ browserify-css --minify=true --output bundle.css ] -o bundle.js app.js
```
