### ISSUE TITLE
Security: Update `find-node-modules` to resolve `braces` vulnerability

### ISSUE THREAD

**Issue by G-Rath** [cheton/browserify-css#66]
>   Low             Regular Expression Denial of Service                          
>                                                                                 
>   Package         braces                                                        
>                                                                                 
>   Patched in      >=2.3.1                                                       
>                                                                                 
>   Dependency of   browserify-css [dev]                                          
>                                                                                 
>   Path            browserify-css > find-node-modules > findup-sync >            
>                   micromatch > braces                                           
>                                                                                 
>   More info       https://npmjs.com/advisories/786   

I have made an [comment requesting a new version of `micromatch@2.x.x`](https://github.com/micromatch/micromatch/issues/148#issuecomment-492029264) be released with an update to the `braces` dependency, which might happen and thus resolve this.

However, ideally `browserify-css` should update `find-node-modules` to `v2.0.0`, to resolve this security vulnerability.

**Comment by AsinusRex** [comment]
Also hoping for a dependency version bump up to get rid of the vulnerability. Doing it by hand introduces a whole new process to deployment.
